stages:
  # Ensure Annif is installed
  install:
    cmd:
    - python3 -m venv venv
    - . venv/bin/activate && pip install -U pip wheel setuptools && pip install -r requirements.txt
    - cp requirements.txt venv-installed
    deps:
    - requirements.txt
    outs:
    - venv-installed:
        cache: false
  # Load YSO vocabulary
  load-vocab:
    cmd: venv/bin/annif load-vocab --force yso corpora/yso-skos.ttl
    deps:
    - venv-installed
    - corpora/yso-skos.ttl
    outs:
    - data/vocabs/yso
